# Generated by Django 4.2 on 2023-04-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools_box',
            field=models.CharField(choices=[('django', 'Django'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('python', 'Python')], default='django', max_length=255),
        ),
    ]
