# Generated by Django 4.2.6 on 2024-09-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_tools_box2_project_tools_box3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_box',
            field=models.CharField(choices=[('django', 'Django'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('python', 'Python'), ('fastAPI', 'FastAPI'), ('Flask', 'Flask')], default='django', max_length=255, verbose_name='Used tools'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_box2',
            field=models.CharField(blank=True, choices=[('django', 'Django'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('python', 'Python'), ('fastAPI', 'FastAPI'), ('Flask', 'Flask')], max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_box3',
            field=models.CharField(blank=True, choices=[('django', 'Django'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('python', 'Python'), ('fastAPI', 'FastAPI'), ('Flask', 'Flask')], max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_box4',
            field=models.CharField(blank=True, choices=[('django', 'Django'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('python', 'Python'), ('fastAPI', 'FastAPI'), ('Flask', 'Flask')], max_length=255),
        ),
    ]
