# Generated by Django 4.2.6 on 2024-09-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_image_alter_project_tools_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tools_box2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tools_box3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tools_box4',
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_box',
            field=models.JSONField(),
        ),
    ]
